name: Main
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

env:
  # shivammathur/setup-php
  PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
  PHP_VERSION: 8.1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none
          tools: composer:v2
      - name: Validate composer files
        run : composer validate 
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: PHPCS
        run: php vendor/bin/phpcs
      - name: PHPStan
        run: php vendor/bin/phpstan analyze

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
      with:
        name: drupal-artifcat
        path: ./

  
  